<?php
// define('USER', 'user15');
// define('PASSWD', 'user15');
define('USER', 'root');
define('PASSWD', '');
define('HOST', 'localhost');
define('DBNAME', 'user15');
define('DSN', 'mysql:dbname=user15; host=localhost');
define('LOGFORM', 'this password or email does not exist, or you need to register !');
define('RECURENT_ERROR', 'Sorry, check type recurent !');
define('PASSWD_ERROR', 'parols are not equal');
define('REGISTER_SUCCESS', 'congrats, you are registered!');
define('COUNT_ERR_SYMBOL', 'please enter min 4  symbols in the parol fild and min 3 symbols in the other filds !');
define('COUNT_ERR_SYMBOL_PASSWD', 'enter password more then 3 symbols !');
define('ERR_EMAIL', 'your Email isnt VALID !');
define('CHECK_NOTE_FILD', 'Please fill the note fild !');
define('EMPTY_FILDS_TIMES_DURATION', 'Please check count and how many times of the event do you want !');
define('NO_DATA', 'Ups, something is going wrong we is fixing this problem !');
define('NO_ROOM', 'Please check the room !');
define('NO_DATE', 'Please pick a date  !');
define('NO_DATA_TIME_NOTE', 'Please pick a start-end time and fill notelist !');
define('EDD_SUCCESS', "Congrats, You book this room ! ");
define('EDD_ERROR', 'SORRY, Something is going wrong, you can`t book !');
define('ERROR_TIME', 'Please enter corect time !');
define('ERR_WEEKEND', 'Please choose only work days in the week !');
define('BUSY_TIME', 'Time is busy! please pick another time. ');
define('ERROR_USERS', ' Employee list is empty! please add user.');
define('ERROR_USER', ' This user does not exist.');
define('DATA_UPDATED', ' Information about user is updated.');
define('ERROR_UPDATE', ' Failure Information is not updated !.');
define('SUCCESS_DELETE_USER', ' You deleted user successfully !.');
define('ERROR_DELETE_USER', ' You CANT DALETE this user !.');

